config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/index'
  get 'enrollments/show'
  get 'enrollments/new'
  get 'courses/index'
  get 'users/show'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  # log in as a test user
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:new, :create]
  end

  resources :chapters, only: [:update]
  resources :enrollments, only: [:index, :show, :update]
  resources :users, only: :show

  # routes for 'follow / unfollow a user' feature
  post 'users/:id/follow', to: 'users#follow', as: :follow_user
  post 'users/:id/unfollow', to: 'users#unfollow', as: :unfollow_user

  # routes for 'search for a user' feature
  get '/users', to: 'users#index', as: :users

  # route to scrape Duolingo
  get '/user/:id', to: 'users#scrape_duolingo', as: :user_scrape_duolingo

  # left as a memo for Merit gem
  # devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_many :platforms, -> { distinct }, through: :courses
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable, :omniauthable

  # SETUP for gem acts_as_favoritor https://github.com/jonhue/acts_as_favoritor#setup
  # -  Add acts_as_favoritable to the models you want to be able to get favorited:
  acts_as_favoritable
  # - Specify which models can favorite other models by adding acts_as_favoritor:
  acts_as_favoritor
  has_merit

  def leaderboard_friends_for(course)
    # should return an array of enrollments
    # users_ids is an array of users ids including current_user id and followed users id
    users_ids = favorited_users.pluck(:id) + [id]
    Enrollment.where(user: users_ids, course: course).order(completion_status: :desc)
  end

  def enrollments_for(platform)
    enrollments.joins(:course).where(courses: { platform: platform })
  end

  # test user
  # def self.guest
  #   find_by(email: 'test@example.com')
  # end

  # omniauth
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        # email:    User.dummy_email(auth),
        # password: Devise.friendly_token[0, 20]
      )
    end
    user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  def github
    callback_from :github
  end

  def linkedin
    callback_from :linkedin
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    # redirect_back(fallback_location: root_path), notice: "Logged in as a test user"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
    # added by recommendation of rails_best_practices
    @favorite = User.find(favorite.favoritable_id)
    authorize @favorite
  end

  def scrape_duolingo
    @platform = Platform.find_by(name: "Duolingo")
    @user = User.find(params[:id])
    authorize @user
    # scraping all leaderboard friends
    # users = @user.enrollments_for(@platform).map do |enrollment|
    #   @user.leaderboard_friends_for(enrollment.course)
    # end
    # users.flatten.map(&:user).uniq.each do |user|
    #   puts "scraping data for #{user.name}"
    #   p stats = DuolingoScraper.new(user).scrape
    # end
    previous_xp = @user.enrollments_for(@platform).sum(:completion_status)
    # TODO: Uncomment below when working on Heroku
    p DuolingoScraper.new(@user).scrape
    @user.reload
    new_xp = @user.enrollments_for(@platform).sum(:completion_status)
    # add one streak
    if previous_xp != new_xp
      @user.streak += 1
      @user.save
    end
    # TODO: Delete these 3 lines when working on Heroku
    # Shogo added these 3 lines from line 36-38 of duolingo_scraper.rb
    # enrollment = @user.enrollments.joins(:platform, :course).find_by("courses.title = :title AND platforms.name = :platform", title: "Japanese", platform: "Duolingo")
    # enrollment.completion_status += 5
    # enrollment.save

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.js
    end
  end

  def index
    if params[:query].present?
      @users = policy_scope(User).where(name: params[:query])
    else
      @users = policy_scope(User)
    end
    # authorisation error - https://github.com/varvet/pundit#ensuring-policies-and-scopes-are-used
    # see example from courses_controller.rb
  end

  # method for current_user to follow another user
  def follow
    @user = User.find(params[:id])
    authorize @user
    current_user.favorite(@user)
    redirect_to request.referrer
  end

  # method for current_user to unfollow another user
  def unfollow
    @user = User.find(params[:id])
    authorize @user
    current_user.unfavorite(@user)

    redirect_to request.referrer
  end

   # method for current_user to see the list of other users he/she is following
  # def following
  #   current_user.all_favorites
  # end

  # # method for current_user to see the list of other users he/she is being followed by
  # def followers
  #   current_user.all_favorited
  # end

  private

  # WARNING - DO NOT USE this commented out code please - I wish to keep it purely for future reference (Julien)
  # def get_enrollment_stats
  #   # this method loads stats for all the enrollments inside of @stats
  #   @stats = {}
  #   # get all the enrollments with current_user.enrollments
  #   current_user_enrollments = current_user.enrollments  # returns an array of enrollment instances
  #   # iterate over that array of enrollments
  #   current_user_enrollments.map do |enrollment|
  #     # 1 - check which platform each enrollment is for
  #     # 2 - use relevant scraper to get that structured data for that enrollment
  #     #  - need to specify the platform name to able to render the correct card in the view with the conditional statement (e.g. stat.platform)
  #     case enrollment.course.platform.name
  #     # julien = User.find(7)
  #     # julien.enrollments.first.course.platform.name returns "Codecademy"
  #     when 'Duolingo'
  #       # julien.enrollments.first.completion_status returns 30
  #       # duolingo_scraped_data is an array of hashes like  [{:language=>"Spanish", :xp_points=>"7037"}, {:language=>"Korean", :xp_points=>"4770"}, ...]
  #       @stats[:duolingo] = DuolingoScraper.new(@user).scrape
  #       # { duolingo:[{:language=>"Spanish", :xp_points=>"7037"}, {:language=>"Korean", :xp_points=>"4770"}, ...] }
  #     end
  #   end
  #   # 3 - push that data into @stats
  #   return @stats
  # end
end

app/views/users/_streaks.html.erb
<div class="new-streak-section demo-hover">
  <h5 class="card-title-font">Streaks</h5>
  <div class="d-flex justify-content-center align-items-center">
    <i class="fas fa-fire-alt fa-fire-alt-big mx-0"></i>
    <div class="streak-bubble mr-5">
      <p class="streak-text-font">Current Streak</p>
      <p class="streak-number-font"><%= user.streak %> days</p>
    </div>
    <i class="fas fa-fire-alt fa-fire-alt-big fire-yellow ml-3"></i>
    <div class="streak-bubble">
      <p class="streak-text-font">Longest Streak</p>
      <p class="streak-number-font">77 days</p>
  </div>
</div>

app/views/users/index.html.erb
<!-- TODO: insert navbar -->
  <div>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon gray-background">
    <%= link_to "OneBite", root_path, class: "onebite-home-orange"  %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a href="https://calendar.google.com/calendar/" class="nav-link navbar-link-text-orange" target="_blank">Calendar</a>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link navbar-link-text-orange mx-3" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/deyqjsowe/image/upload/v1589709320/Yun_Chung_Profile_Photo_2_rlfgi5.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Help", "#", class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path(current_user), method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

<!-- BEGINNING - search form to look for a friend  -->
<%= form_tag users_path, class: "navbar-searchbar mt-4 mb-3 mx-auto", method: :get do %>
<div class="d-flex index-searchbar">

  <%= text_field_tag :query, params[:query], class: "form-control banner-searchbar-round index-searchbar", placeholder: "Find friends to follow" %>
  <%= submit_tag "Find Friends", class: "btn btn-primary index-searchbar banner-searchbar-roundbutton" %>
<% end %>
</div>
  <!-- form taken from the lecture on Search  -->
<!--   <%#= form_tag users_path, method: :get do %>
    <%#= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a friend" %>
    <%#= submit_tag "Search", class: "unfollow-button" %>
  <%# end %> -->
<!-- END - search form to look for a friend  -->



<!-- BEGINNING - the list of friends from the search in show.html.erb -->
<div class="users-index-container container">
<!--   <h1>Find your friends</h1>
 -->  <div class="row">
    <div class="col-sm-8 offset-sm-2">

      <div id="users">
        <% @users.each do |user| %>
          <div class="card-courses-users-index m-3">
            <div>
              <img class="mx-3 avatar-users-index-bordered-new" alt="avatar-bordered" src="<%= ['https://res.cloudinary.com/deyqjsowe/image/upload/v1591165384/WooChaHee_satbqe.jpg', 'https://kitt.lewagon.com/placeholder/users/sarahlafer', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591166442/pjoe_esm4oc.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591166442/bennifer_keahqo.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591166442/jonoh_glkc4f.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591166442/julie_l5se6x.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591166444/janet_qmt3wf.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591166613/mickles_ax06yk.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591166730/virginia_ucqyxr.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591171439/sunmi_xg1mwc.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591171439/uncle_zqr4sn.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591171439/yura_ueelw4.jpg', 'https://res.cloudinary.com/deyqjsowe/image/upload/v1591171439/borrah_zrkopm.jpg'].sample %>" />
            </div>

            <div class="card-courses-index-infos justify-content-around results-info-left">
              <h2 class="index-card-title-font user-index-card-name"><%= link_to user.name.capitalize.to_s, user_path(user), class: "user-index-card-name" %></h2>

              <div class="d-flex">
                <p class="index-card-description-user-font"><%= rand(100) %>-day streak  |</p>
              <% user.badges.each do |badge| %>
                <p><<%= badge.name %></p>
              <% end %>
              <p>| <%= user.points + rand(1..15) %> points</p>
              </div>

              <!-- test for Merit gem, badges and points -->

              <div class="d-flex">
                <% if user.courses == [] %>
                  <p class="mr-3 new-course-title">Currently not enrolled in any courses.</p>
                <% elsif user.courses %>
                  <% user.courses.each do |course|  %>
                    <%= link_to course.title, course_path(course), class: "mr-3 new-class-url-link", target: :_blank %>
                  <% end %>
                <% end %>
              </div>
<!--
<a href="<%#= course_path %>" class="new-class-url-link" target="blank"><p class="mr-3 new-course-title"><%#= course.title %></p></a> -->



              <!-- test ends -->

            </div>
            <div class="card-users-index-buttons mx-3">
              <% if current_user.favorited?(user) %>
                <%= link_to "Unfollow", unfollow_user_path(user), class: "button-follow index-card-goto-show-font btn unfollow-button", method: :post, remote: true %>
              <% else %>
                <%= link_to "Follow", follow_user_path(user), class: "index-card-goto-show-font btn btn-onebite-orange button-unfollow", method: :post, remote: true %>
              <% end %>
              <%# raise %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- END - the list of friends from the search in show.html.erb -->

app/views/users/scrape_duolingo.js.erb
document.querySelector(".leaderboard-duolingo").innerHTML = "<%=j render 'platforms/duolingo_leaderboard', enrollments: @user.enrollments_for(@platform) %>"
document.querySelector("#streaks").innerHTML = "<%=j render 'users/streaks', user: @user %>"
document.querySelector(".btn-sync").addEventListener("click", () => {
  document.querySelector(".loading-container").classList.add("loading")
  document.querySelector(".btn-sync").remove()
})