config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/index'
  get 'enrollments/show'
  get 'enrollments/new'
  get 'courses/index'
  get 'users/show'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  # log in as a test user
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:new, :create]
  end

  resources :chapters, only: [:update]
  resources :enrollments, only: [:index, :show, :update]
  resources :users, only: :show

  # routes for 'follow / unfollow a user' feature
  post 'users/:id/follow', to: 'users#follow', as: :follow_user
  post 'users/:id/unfollow', to: 'users#unfollow', as: :unfollow_user

  # routes for 'search for a user' feature
  get '/users', to: 'users#index', as: :users

  # route to scrape Duolingo
  get '/user/:id', to: 'users#scrape_duolingo', as: :user_scrape_duolingo

  # left as a memo for Merit gem
  # devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>

  <div>
    <p>© 2020 OneBite Inc. All rights reserved.</p>
  </div>

</div>

app/views/shared/_leaderboards.html.erb
<!-- TODO: display a card for each enrollment of a user -->
  <!-- iterate over each platform -->
  <!-- for each platform iterate over each course -->
  <!-- for each course iterate over each enrollment -->
  <!-- display the card associated with enrollment -->
  <!-- find all the friends from current_user who are taking the same course -->

<% user.platforms.each do |platform| %>
  <% case platform.name %>
  <% when 'Duolingo' %>
  <div class="leaderboard-duolingo  demo-hover">
    <%= render 'platforms/duolingo_leaderboard', enrollments: user.enrollments_for(platform) %>
  </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login as a test user", users_guest_sign_in_path, method: :post, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>