config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/index'
  get 'enrollments/show'
  get 'enrollments/new'
  get 'courses/index'
  get 'users/show'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  # log in as a test user
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:new, :create]
  end

  resources :chapters, only: [:update]
  resources :enrollments, only: [:index, :show, :update]
  resources :users, only: :show

  # routes for 'follow / unfollow a user' feature
  post 'users/:id/follow', to: 'users#follow', as: :follow_user
  post 'users/:id/unfollow', to: 'users#unfollow', as: :unfollow_user

  # routes for 'search for a user' feature
  get '/users', to: 'users#index', as: :users

  # route to scrape Duolingo
  get '/user/:id', to: 'users#scrape_duolingo', as: :user_scrape_duolingo

  # left as a memo for Merit gem
  # devise_for :users, controllers: { registrations: 'users/registrations' }
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!,
  def index
    if params[:query].present?
      @courses = policy_scope(Course).search_by_title(params[:query])
    else
      @courses = policy_scope(Course)
    end
  end


  def show
    # scraper = CodecademyScraper.new(@course.platform_id)
    # scaper.perform_scraping
    @course = Course.find(params[:id])
    authorize @course
  end
end

app/views/courses/index.html.erb
<div>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon gray-background">
    <%= link_to "OneBite", root_path, class: "onebite-home-orange"  %>

        <%= form_tag courses_path, class: "navbar-searchbar mx-3", method: :get do %>
      <div class="d-flex">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control banner-searchbar-round",
          placeholder: "What would you like to learn?"
          %>
          <%= submit_tag "Search", class: "btn btn-primary banner-searchbar-roundbutton" %>
        <% end %>
      </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a href="https://calendar.google.com/calendar/" class="nav-link navbar-link-text-orange" target="_blank">Calendar</a>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link navbar-link-text-orange mx-3" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/deyqjsowe/image/upload/v1589709320/Yun_Chung_Profile_Photo_2_rlfgi5.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Help", "#", class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path(current_user), method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

<%# raise %>

<div class="container my-3 ">
  <h2 class="results-h2 text-center">Recommended Courses</h2>
  <% @courses.each do |course| %>
    <div class="card-courses-index m-3 demo-hover">
      <% if course.platform_name == 'Codecademy' %>
        <img src="https://res.cloudinary.com/deyqjsowe/image/upload/v1590563366/squarecodecademylog_kxokkd.png" />
      <% elsif course.platform_name == 'Udemy' %>
        <img src="https://res.cloudinary.com/deyqjsowe/image/upload/v1590646495/udemy_square_frdkbs.png" />
      <% elsif course.platform_name == 'Coursera' %>
        <img src="https://res.cloudinary.com/deyqjsowe/image/upload/v1590722085/coursera-logo-square_y0yukg.webp" />
      <% elsif course.platform_name == 'Duolingo' %>
        <img src="https://i.pcmag.com/imagery/reviews/00MFRjnTbz8iv8USK3YZd7T-7.fit_scale.size_1028x578.v_1569475584.png" />
      <% elsif course.platform_name == 'Wanikani' %>
        <img src="https://pbs.twimg.com/profile_images/1213575248911552512/WP11ESTy_400x400.jpg" />
      <% end %>

      <div class="card-courses-index-infos justify-content-around results-info-left">
        <h2 class="index-card-title-font"><%= course.title %></h2>
        <p class="index-card-description-font"><%= course.description %></p>
<!--         <p class="index-card-time-font">Time to complete: <%#= course.expected_time_to_complete %></p> -->
        <p class="index-card-diff-font friends-font mt-3"><strong class="demo-hover-font"><%= course.cost %></strong> people are enrolled in this class.</p>
        <p class="index-card-diff-font friends-font">Your friends, <strong class="demo-hover-font"><%= course.difficulty %></strong>, are enrolled in this course.</p>
        <%= link_to "See details", course_path(course), class: "index-card-goto-show-font btn btn-onebite-orange mt-2" %>
        <p class="index-card-rating-font"><%= course.rating %></p>
      </div>
      <div class="results-info-right">
        <%#= link_to "#{course.platform.name}", course.url, class: "btn btn-outline-dark" %>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/show.html.erb
<div class="banner-showpage" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/deyqjsowe/image/upload/v1590482198/code-coding-computer-data-574077_kghvqx.jpg );">

	<div class="navbar navbar-onebite	navbar-expand-sm navbar-light navbar-lewagon gray-background">
	  <%= link_to "OneBite", root_path, class: "onebite-home-orange"  %>

	  		<%= form_tag courses_path, class: "navbar-searchbar mx-3", method: :get do %>
			<div class="d-flex">
			  <%= text_field_tag :query,
			    params[:query],
			    class: "form-control banner-searchbar-round",
			    placeholder: "What would you like to learn?"
			  	%>
		  		<%= submit_tag "Search", class: "btn btn-primary banner-searchbar-roundbutton" %>
				<% end %>
			</div>

	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	      	<a href="https://calendar.google.com/calendar/" class="nav-link navbar-link-text-orange" target="_blank">Calendar</a>
	      </li>
	      <li class="nav-item">

	      	<%# if current_user %>
	        <%= link_to "Profile", user_path(current_user), class: "nav-link navbar-link-text-orange mx-3" %>
	      	<%# else %>
				<%#= link_to "Profile", user_path(current_user), class: "nav-link navbar-link-text-orange mx-3" %>
	      	<%# end %>



	      </li>
	      <li class="nav-item dropdown">
	        <%= image_tag "https://res.cloudinary.com/deyqjsowe/image/upload/v1589709320/Yun_Chung_Profile_Photo_2_rlfgi5.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
	        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
	          <%= link_to "Help", "#", class: "dropdown-item" %>
	          <%= link_to "Log Out", destroy_user_session_path(current_user), method: :delete, class: "dropdown-item" %>
	        </div>
	      </li>
	    </ul>
	  </div>
	</div>

  <div class="container banner-text-container">
    <h1 class="banner-h1"><strong><%= @course.title %></strong></h1>
    <p class="banner-p"><%= @course.platform_name %></p>
    <!-- <a class="btn banner-enroll-roundbutton text-white" href="#">Enroll now</a>  -->
    <%= link_to "Enroll now", new_course_enrollment_path(@course), class: "btn banner-enroll-roundbutton text-white"  %>
  </div>
</div>

<div class="container my-3 same-font">
	<div class="show-info-section">
		<div class="show-info-left mx-3  rounded-box demo-hover">
			<div>

        <p class="index-card-diff-font friends-font-show mt-3"><strong class="demo-hover-font"><%= @course.cost %></strong> people are enrolled in this class.</p>
        <p class="index-card-diff-font friends-font-show">Your friends, <strong class="demo-hover-font"><%= @course.difficulty %></strong>, are enrolled in this course.</p>
        <br>

				<h3 class="mb-3 course-font"><strong>What you'll learn.</strong></h3>
			</div>
		  <% @course.chapters.each do |chapter| %>
  			<%# if chapter.done %>
          <p><%= chapter.name %></p>
        <%# else %>
          <!-- <p><%#= chapter.name %> ☐</p> -->
          <%#= simple_form_for chapter do |f| %>
            <%#= f.input :done %>
          <%# end %>
        <%# end %>
			<% end %>
		</div>

		<div>
			<div class="show-info-right mx-3 rounded-box demo-hover">
				<h3 class="course-font"><strong><%= @course.title %></strong></h3>
				<h6 class="platform-font"><%= @course.platform_name %></h6>
				<h6><%= @course.description %></h6>
				<br>
        <%# if @course.expected_time_to_complete == "Not Applicable" %>
				<h6>Time to complete: <strong class="demo-hover-font"><%= @course.expected_time_to_complete %></strong></h6>
        <%# else %>
          <!-- <h6 class="">Time to complete: <%#= @course.expected_time_to_complete %> hours</h6> -->
        <%# end %>
			</div>
				<%= link_to 'Back to results', courses_path, class: "navbar-link-text-orange m-5 back-to-results" %>
			</div>
	</div>
</div>